pub const CONFIG: &str = "/.gsConfig";  // path of config file
pub const UNTAGGED: &str = "untagged";  // when match not found for autogenerated aliases

// items in the arg vector when processing options
pub const FILTERS   : usize = 0;
pub const EXCLUDE   : usize = 1;
pub const SEARCH    : usize = 2;
pub const CI_SEARCH : usize = 3;
pub const BRANCHES  : usize = 4;

// certain time variables in seconds for checking commit recency
pub const HOURS     : i64 = 60*60;
pub const DAYS      : i64 = 24*HOURS;
pub const WEEKS     : i64 = 7*DAYS;
pub const MONTHS    : i64 = 30*DAYS;
pub const YEARS     : i64 = 52*WEEKS;
